#!/usr/bin/env python3
import klib
import getpass
import argparse
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--email",help="1014211@student.crsd.org")
    parser.add_argument("--password",help="1014211")
    parser.add_argument("--pin",help="The game pin")
    parser.add_argument("--name",help="nat bernard")
    parser.add_argument('--random_question', action="store_true")
    parser.add_argument('--random_answer', action="store_true")
    args = parser.parse_args()
    for key, val in vars(args).items():
        if val is None:
            val = input(f'{key} > ')
            setattr(args, key, val)
    try:
        user = klib.Kahoot(args.pin, args.name)
        user.random_question = args.random_question
        user.random_answer = args.random_answer
        user.authenticate(args.email, args.password)
        user.startGame()
    except KeyboardInterrupt:
        print('EXITING...')
        exit()
